### ISSUE TITLE
hoverでの行変色を特定列だけ対象外にしたい

### ISSUE THREAD

**Issue by sky-to-heaven** [sky-to-heaven/test1#6]
こんな感じに変色を反映させたくない列を除外してtdに設定する
```html
 <style type="text/css">
    #table2 tr:hover td:not(.noHover) {
        background-color:green;
    }
```
またはこんな感じにして反映させたいtdにクラスをつけるのでも可
※TailWindはnotが使えないように見えるのでこっちになる？ そんなことない？
```html
<style type="text/css">
    #table1 tr:hover td.withHover {
        background-color: #ffdaf8;
    }
```

**Comment by sky-to-heaven** [comment]
Tailwindcssだと:not()は[]で囲んで直記述で使えなくもない模様
※無理やりやるので壊れるケースもあったりなかったりする
となるとこんな感じか？
```css
tr:hover [&:not(.nohover)]:bg-green-400
```
なんかもう素直にこんな感じで上書きするのが一番早そうな気がしてきた
```css
#table1 tr:hover td {
    background-color: #ffdaf8;

}
#table1 tr:hover td.noHover {
    background-color: transparent;
}
```
